### ISSUE TITLE
allow campaign sponsor or doner to specify other name

### ISSUE THREAD

**Issue by nairdo** [JordanRift/Grassroots#2]
Such as "anonymous donor" or "car wash" or "grandma jones".

**Comment by dustinpatrick** [comment]
this looks great, for the example can we say "car wash" or "anonymous" instead of 'santa clause"

**Comment by JasonOffutt** [comment]
Yep. The placeholder text is negotiable. If you'd prefer something other than 'Santa Clause' let me know.

**Comment by dustinpatrick** [comment]
Now that I'm looking at it, does the "comment" field serve the purpose of the "display name" field?  Check out Law Sisters campaign donors and one of them in Karlie who wrote in car wash... let me know what you think

**Comment by JasonOffutt** [comment]
The display name field represents the person or entity who donated. The comments field are an optional free-form text block.

**Comment by JasonOffutt** [comment]
I'm going to to ahead and close this feature request for now. If there are any bugs, please create a new issue for it. If this feature addition needs to be discussed further, please reopen.
