### ISSUE TITLE
require account profile for donation

### ISSUE THREAD

**Issue by nairdo** [JordanRift/Grassroots#3]
Required users to create account before being able to donate.

**Comment by JasonOffutt** [comment]
Will add [Authorize] to the DonateController declaration for now as a short term fix.

**Comment by dustinpatrick** [comment]
I think its too clunky to use for now.  I'd rather wait until its a little cleaner to unroll this.

**Comment by JasonOffutt** [comment]
Removing [Authorize] attribute from DonateController class.
