### ISSUE TITLE
make progress bar optional

### ISSUE THREAD

**Issue by nairdo** [JordanRift/Grassroots#4]
When starting a new system, the goal numbers grow, but the % amount collected declines. That is discouraging and has the opposite intended effect.  Later on re-enable it so it looks cool and generates excitement again about progress.

**Comment by dustinpatrick** [comment]
each campaign keeps its own progress bar but the overall campaign progress bar goes away and is replaced with text "launch a campaign" with an arrow to the get started button or something.

**Comment by JasonOffutt** [comment]
Added a new OrganizationSetting to allow custom HTML to be injected in place of the progress bar.

**Comment by JasonOffutt** [comment]
Closing feature request for now. Technical requirements are met. We'll review the content via email this week.
